# Set nginx base image
FROM nginx

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf

# COPY static/*.html remote/static/
# COPY static/*.js remote/static/